### ISSUE TITLE
Small question about docker_data

### ISSUE THREAD

**Issue by pierpaolocira** [lombax85/docker-apache-mysql-php-mongo#1]
Hi,
thank you for this work: it is exactly what I need.

I have (I hope not very stupid) question: I'm a Mac user, and after following your instruction (manual install, my html files are in a subfolder that i configured into .env) and running the container, I still continue not to see the "docker_data" folder.

I'm using the master branch.

Do you have any idea about, or a suggestion in order to understand where that folder is?

Thank you

**Comment by lombax85** [comment]
Hi, 

some questions
- can you attach please your .env file content? 
- did you check the "File Sharing" section in your Docker Configuration? 
- Any error in console?

**Comment by pierpaolocira** [comment]
Hi, than you for your quick reply.

This is my [.env file](https://github.com/lombax85/docker-apache-mysql-php-mongo/files/600629/my.env.txt) (don't care the name: I just modified it in order to succesfully upload)

In any case I just noted that there is this row: `DOCKER_DATA_DIRECTORY=docker/data`, so I think that there is just a disalignment between documentation (README file) and config file.

In effect in docker/data I can find the following folders: couchdb, memcached, mongo, mysql, sessions that are exactly the data folders (I verified the content of mysql).

So I think this issue can be closed just aligning those two files.

Another note is related to your "File Sharing" question: I wasn't able to do what you say just because my Docker installation (I just installed yesterday the latest release) already shares /Volumes (so when I try to share ./docker, Docker alerts me that it isn't neessary because ./docker is obviously a subfolder of /Volunes).

Thank you for your time and your work (I'm going to open another unrelated issue :D)

**Comment by lombax85** [comment]
Ok, I confirm that ./docker/data is your default data directory when you install "manually", I'll update the default .env files or the README in the next release. 
About file sharing, I'll update the README adding more informations about how File Sharing works in this case.
Thank you
Regards
Fabio

**Comment by lombax85** [comment]
(or feel free to make a pull request if you want :-)

**Comment by pierpaolocira** [comment]
I think if ./docker/data is used only in manual mode, it should be better to set is as ./docker_data in order to keep everything aligned.

If this is the only modification I can make a pull request (this is my first day with Docker, so I'm not a great expert :) ).

Pierpaolo

**Comment by lombax85** [comment]
If you want, only two modifications: 
- in .env.default, change DOCKER_DATA_DIRECTORY from `docker/data` to `docker_data` (no leading or trailing slash)
- add `/docker_data` to the .gitignore file

I'll test manually before merging. Thanks

**Comment by pierpaolocira** [comment]
Ok, did it (including another small related error in a comment of .env.composer)...

Before requesting for a pull, do you think is it really necessary to add that folder to the .gitignore?
Consider that it now just contains the following:

```
.DS_Store
.env
/project
.idea
```

(So not any reference to that folder in a wrong position)

**Comment by lombax85** [comment]
Yes, docker_data should be ignored, now it is not in the .gitignore by mistake :-) (I'm working on this repo mainly for the composer integration, with composer integration the .gitignore is not necessary since the .gitignore file is the one of the main project. For this reason the "manual mode" is less tested and there is some mistake)

**Comment by pierpaolocira** [comment]
Ok, done.
In any case, I understand... by the way I found it useful for my needs (a php+mysql+mongo project) and I'm using it on an existing long project... so I can continue testing the manual mode :)

**Comment by lombax85** [comment]
Merged, thank you. Quick info: I'm working on a quicker way to install this project via composer, [have a look at this repo](https://github.com/lombax85/phpdocker)
