### ISSUE TITLE
Allow parametrisation of MongoDB version

### ISSUE THREAD

**Issue by pierpaolocira** [lombax85/docker-apache-mysql-php-mongo#4]
Hi,
I think, such as for PHP, to allow users to choose the most suitable PHP version they need.

My idea is to allow to choose between 2.6, 3.0, and latest (currently 3.1 in MongoDB docker repository).

If you think it is suitable I can do it. Something like:
`# MongoDB version: latest version use Dockerfile, v3.0 use Dockerfile-30, v2.6 use Dockerfile-26,
MONGODB_DOCKERFILE=Dockerfile`
and the relevant part in `docker-compose.yml`

**Comment by lombax85** [comment]
it's ok for me, waiting for a feedback about testing #6 before merging

**Comment by lombax85** [comment]
closed after merge
