### ISSUE TITLE
Drush doesn't work properly

### ISSUE THREAD

**Issue by pierpaolocira** [lombax85/docker-apache-mysql-php-mongo#5]
Hi,
I tried to use "drush" by setting `INSTALL_DRUSH=true` into "workspace" configurations.

Due to the nature of Drush it isn't able to properly work if the system misses for a way to connect to the database.
More specifically: it needs for the "mysql-client" installed package into th "workspace" in order to work properly.

I kwnow this is can be classified as a "php-fpm" bug, but you have to also consider that this "docker-apache-mysql-php-mongo" configuration already comes with mysql (meanwhile in php-fpm it is not sure).

This is why I suggest to modify the Docker file of the workflow in order to also install the mysql client if INSTALL_DRUSH is enabled.

**Comment by lombax85** [comment]
Ok, i'll have a look to all bugs - including this - during the next weekend, but as always feel free to make a pull request if you prefer. Thanks
Fabio

**Comment by lombax85** [comment]
Sorry for the delay. I merged your PR. Thanks
